routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('estudiante', 'EstudianteController');
Route::resource('empleado', 'EmpleadoController');
Route::resource('libro', 'LibroController');
Route::resource('prestamo', 'PrestamoController');

Route::get('/', function () {
    return view('home');
});

app/Libro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
     /**
     * @var array
     */
    protected $guarded =[];
}

app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Libro;
use Illuminate\Http\Request;

class LibroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $libros = libro::all();
        return view('libro.index', compact('libros'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('libro.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd ($request->all ());
        $validated = $request->validate([
            'nombre' => 'required|string|min:10|max:50',
            'editorial' => 'required|string|min:10|max:150',
            'anio' => 'required|date',
            'ubicacion' => 'required|string|min:10|max:150',
            'autor' => 'required|string|min:10|max:150',
            'tipo' => 'required|string|min:10|max:150',
            'area' => 'required|string|min:1',
            'dias-prestamo' => 'required|numeric|min:1',

        ]);

        $libro = libro::create($validated);
        return redirect()->route('libro.show' , $libro)->withSuccess('Servicio creado con exito!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function show(Libro $libro)
    {
        return view('libro.show',compact('libro'));        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function edit(Libro $libro)
    {
        return view('libro.edit', compact('libro'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Libro $libro)
    {
        $validated = $request->validate([
            'nombre' => 'required|string|min:10|max:50',
            'editorial' => 'required|string|min:10|max:150',
            'anio' => 'required|date|',
            'ubicacion' => 'required|string|min:10|max:150',
            'autor' => 'required|string|min:10|max:150',
            'tipo' => 'required|string|min:10|max:150',
            'area' => 'required|string|min:1',
            'dias-prestamo' => 'required|numeric|min:1',
        ]);

        $libro->fill($validated);
        $libro->save();
        return redirect()->route('libro.show' , $libro)->withSuccess('Servicio editado con exito!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function destroy(Libro $libro)
    {
        $libro->delete();
        return redirect()->route('libro.index')->withSuccess('Servicio borrado con exito');
    }
}

resources/views/libro/create.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Registrar Estudiante</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('libro.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" value="{{ old('nombre') }}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="editorial" class="col-md-4 col-form-label text-md-right">Editorial</label>

                            <div class="col-md-6">
                                <input id="editorial" type="text" class="form-control{{ $errors->has('editorial') ? ' is-invalid' : '' }}" name="editorial" value="{{ old('editorial') }}" required autofocus>

                                @if ($errors->has('editorial'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('editorial') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="anio" class="col-md-4 col-form-label text-md-right">Año</label>

                            <div class="col-md-6">
                                <input id="anio" type="text" class="form-control{{ $errors->has('anio') ? ' is-invalid' : '' }}" name="anio" value="{{ old('anio') }}" required autofocus>

                                @if ($errors->has('anio'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('anio') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="ubicacion" class="col-md-4 col-form-label text-md-right">Ubicaciòn en la biblioteca</label>

                            <div class="col-md-6">
                                <input id="ubicacion" type="text" class="form-control{{ $errors->has('ubicacion') ? ' is-invalid' : '' }}" name="ubicacion" value="{{ old('ubicacion') }}" required autofocus>

                                @if ($errors->has('ubicacion'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('ubicacion') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="autor" class="col-md-4 col-form-label text-md-right">Autor</label>

                            <div class="col-md-6">
                                <input id="autor" type="text" class="form-control{{ $errors->has('autor') ? ' is-invalid' : '' }}" name="autor" value="{{ old('autor') }}" required autofocus>

                                @if ($errors->has('autor'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('autor') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="tipo" class="col-md-4 col-form-label text-md-right">Tipo(Normal-Reserva)</label>

                            <div class="col-md-6">
                                <input id="tipo" type="text" class="form-control{{ $errors->has('tipo') ? ' is-invalid' : '' }}" name="tipo" value="{{ old('tipo') }}" required autofocus>

                                @if ($errors->has('tipo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('tipo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                          <div class="form-group row">
                            <label for="area" class="col-md-4 col-form-label text-md-right">Area de conocimiento</label>

                            <div class="col-md-6">
                                <input id="area" type="text" class="form-control{{ $errors->has('area') ? ' is-invalid' : '' }}" name="area" value="{{ old('area') }}" required autofocus>

                                @if ($errors->has('area'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('area') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                          <div class="form-group row">
                            <label for="dias-prestamo" class="col-md-4 col-form-label text-md-right">dias-prestamo de prestamo</label>

                            <div class="col-md-6">
                                <input id="dias-prestamo" type="number" class="form-control{{ $errors->has('dias-prestamo') ? ' is-invalid' : '' }}" name="dias-prestamo" value="{{ old('dias-prestamo') }}" required autofocus>

                                @if ($errors->has('dias-prestamo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('dias-prestamo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Registrar
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/libro/edit.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Registrar Estudiante</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('libro.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" value="{{ libro->nombre }}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="editorial" class="col-md-4 col-form-label text-md-right">Editorial</label>

                            <div class="col-md-6">
                                <input id="editorial" type="text" class="form-control{{ $errors->has('editorial') ? ' is-invalid' : '' }}" name="editorial" value="{{ libro->editorial }}" required autofocus>

                                @if ($errors->has('editorial'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('editorial') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="anio" class="col-md-4 col-form-label text-md-right">Año</label>

                            <div class="col-md-6">
                                <input id="anio" type="text" class="form-control{{ $errors->has('anio') ? ' is-invalid' : '' }}" name="anio" value="{{ libro->anio }}" required autofocus>

                                @if ($errors->has('anio'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('anio') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="ubicacion" class="col-md-4 col-form-label text-md-right">Ubicaciòn en la biblioteca</label>

                            <div class="col-md-6">
                                <input id="ubicacion" type="text" class="form-control{{ $errors->has('ubicacion') ? ' is-invalid' : '' }}" name="ubicacion" value="{{ libro->ubicacion }}" required autofocus>

                                @if ($errors->has('ubicacion'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('ubicacion') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="autor" class="col-md-4 col-form-label text-md-right">Autor</label>

                            <div class="col-md-6">
                                <input id="autor" type="text" class="form-control{{ $errors->has('autor') ? ' is-invalid' : '' }}" name="autor" value="{{ libro->autor }}" required autofocus>

                                @if ($errors->has('autor'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('autor') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="tipo" class="col-md-4 col-form-label text-md-right">Tipo(Normal-Reserva)</label>

                            <div class="col-md-6">
                                <input id="tipo" type="text" class="form-control{{ $errors->has('tipo') ? ' is-invalid' : '' }}" name="tipo" value="{{ libro->tipo }}" required autofocus>

                                @if ($errors->has('tipo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('tipo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                          <div class="form-group row">
                            <label for="area" class="col-md-4 col-form-label text-md-right">Area de conocimiento</label>

                            <div class="col-md-6">
                                <input id="area" type="text" class="form-control{{ $errors->has('area') ? ' is-invalid' : '' }}" name="area" value="{{ libro->area }}" required autofocus>

                                @if ($errors->has('area'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('area') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                          <div class="form-group row">
                            <label for="dias" class="col-md-4 col-form-label text-md-right">Dias de prestamo</label>

                            <div class="col-md-6">
                                <input id="dias" type="text" class="form-control{{ $errors->has('dias') ? ' is-invalid' : '' }}" name="dias" value="{{ libro->dias }}" required autofocus>

                                @if ($errors->has('dias'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('dias') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Registrar
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/libro/index.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @forelse ($libros as $libro)
        @if ($loop->first)
        <div class="col-md-8 text-center">
            <h1>libros Actuales</h1>
        </div>
        @endif
        
        <div class="col-md-8 mt-2">
            <div class="card">
                <div class="card-header"> <a class="btn" href="{{ route('libro.show', $libro) }}"> {{$libro->title}} </a></div>
                <div class="card-body">
                <div>
                    <p>Nombre: {{$libro->nombre}}</p>
                    <p>Editorial: {{$libro->editorial}}</p>
                    <p>Año: {{$libro->anio}}</p>
                    <p>Ubicación en la biblioteca: {{$libro->ubicacion}}</p>
                    <p>Autor: {{$libro->autor}}</p>
                    <p>Tipo: {{$libro->tipo}}</p>
                    <p>Area de conocmiento: {{$libro->area}}</p>
                    <p>Dias prestamo: {{$libro->dias-prestamo}}</p>
                </div>
                </div>
            </div>
        </div>

         <div class=" d-inline-flex ">
            <a href="{{route('libro.edit', $libro)}}" class="btn btn-outline-success btn-md mr-2">Editar</a>
                <form action="{{route('libro.destroy', $libro)}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" href="{{route('libro.edit', $libro)}}" class="btn btn-danger btn-md">Borrar</button>
                    </form>
        </div>


        @empty
        <div class="col-md-8 text-center">
            <h1>Aun no hay libros</h1>
        </div>
        @endforelse

       

    </div>
</div>
@endsection

resources/views/libro/show.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
    
        <div class="col-md-8 text-center">
            <h1>Libros Disponibles</h1>
        </div>
              
        <div class="col-md-8 mt-2">
            <div class="card">
                <div class="card-body">
                <div>
                    <p>Nombre: {{$libro->nombre}}</p>
                    <p>Editorial: {{$libro->editorial}}</p>
                    <p>Año: {{$libro->anio}}</p>
                    <p>Ubicación en la biblioteca: {{$libro->ubicacion}}</p>
                    <p>Autor: {{$libro->autor}}</p>
                    <p>Tipo: {{$libro->tipo}}</p>
                    <p>Area de conocmiento: {{$libro->area}}</p>
                    <p>Dias prestamo: {{$libro->dias-prestamo}}</p>
                </div>
                </div>
            </div>
        </div>
      
    </div>
</div>
@endsection