routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('estudiante', 'EstudianteController');
Route::resource('empleado', 'EmpleadoController');
Route::resource('libro', 'LibroController');
Route::resource('prestamo', 'PrestamoController');

Route::get('/', function () {
    return view('home');
});

app/Estudiante.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Estudiante extends Model
{
     /**
     * @var array
     */
    protected $guarded =[];
}

app/Http/Controllers/EstudianteController.php
<?php

namespace App\Http\Controllers;

use App\Estudiante;
use Illuminate\Http\Request;

class EstudianteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $estudiantes = Estudiante::all();
        return view('estudiante.index', compact('estudiantes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('estudiante.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nombre' => 'required|string|min:5|max:50',
            'apellido' => 'required|string|min:5|max:150',
            'cedula' => 'required|string|min:8',
            'telefono' => 'required|string|min:11',
            'correo' => 'required|string|min:10|max:150',
            'carrera' => 'required|string|min:10|max:150',
        ]);

        $estudiante = Estudiante::create($validated);
        return redirect()->route('estudiante.show' , $estudiante)->withSuccess('Servicio creado con exito!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Estudiante  $estudiante
     * @return \Illuminate\Http\Response
     */
    public function show(Estudiante $estudiante)
    {
        return view('estudiante.show',compact('estudiante'));   
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Estudiante  $estudiante
     * @return \Illuminate\Http\Response
     */
    public function edit(Estudiante $estudiante)
    {
        return view('estudiante.edit', compact('estudiante'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Estudiante  $estudiante
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Estudiante $estudiante)
    {
        $validated = $request->validate([
            'nombre' => 'required|string|min:5|max:50',
            'apellido' => 'required|string|min:5|max:150',
            'cedula' => 'required|string|min:8',
            'telefono' => 'required|string|min:11',
            'correo' => 'required|string|min:10|max:150',
            'carrera' => 'required|string|min:10|max:150',
        ]);

        $estudiante->fill($validated);
        $estudiante->save();
        return redirect()->route('estudiante.show' , $estudiante)->withSuccess('Estudiante agregado con exito ');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Estudiante  $estudiante
     * @return \Illuminate\Http\Response
     */
    public function destroy(Estudiante $estudiante)
    {
        $estudiante->delete();
        return redirect()->route('estudiante.index')->withSuccess('Borrado con exito');
    }
}

resources/views/estudiante/create.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Registrar Estudiante</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('estudiante.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" value="{{ old('nombre') }}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="apellido" class="col-md-4 col-form-label text-md-right">Apellido</label>

                            <div class="col-md-6">
                                <input id="apellido" type="text" class="form-control{{ $errors->has('apellido') ? ' is-invalid' : '' }}" name="apellido" value="{{ old('apellido') }}" required autofocus>

                                @if ($errors->has('apellido'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('apellido') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="cedula" class="col-md-4 col-form-label text-md-right">Cedula</label>

                            <div class="col-md-6">
                                <input id="cedula" type="text" class="form-control{{ $errors->has('cedula') ? ' is-invalid' : '' }}" name="cedula" value="{{ old('cedula') }}" required autofocus>

                                @if ($errors->has('cedula'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('cedula') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="carrera" class="col-md-4 col-form-label text-md-right">Carrera</label>

                            <div class="col-md-6">
                                <input id="carrera" type="text" class="form-control{{ $errors->has('carrera') ? ' is-invalid' : '' }}" name="carrera" value="{{ old('carrera') }}" required autofocus>

                                @if ($errors->has('carrera'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('carrera') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="telefono" class="col-md-4 col-form-label text-md-right">Telefono</label>

                            <div class="col-md-6">
                                <input id="telefono" type="text" class="form-control{{ $errors->has('telefono') ? ' is-invalid' : '' }}" name="telefono" value="{{ old('telefono') }}" required autofocus>

                                @if ($errors->has('telefono'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('telefono') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="correo" class="col-md-4 col-form-label text-md-right">Correo electronico</label>

                            <div class="col-md-6">
                                <input id="correo" type="email" class="form-control{{ $errors->has('correo') ? ' is-invalid' : '' }}" name="correo" value="{{ old('correo') }}" required autofocus>

                                @if ($errors->has('correo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('correo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Registrar
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/estudiante/edit.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Editar Estudiante</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('estudiante.update', $estudiante) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre</label>

                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control{{ $errors->has('nombre') ? ' is-invalid' : '' }}" name="nombre" value="{{ $estudiante->nombre }}" required autofocus>

                                @if ($errors->has('nombre'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="apellido" class="col-md-4 col-form-label text-md-right">Apellido</label>

                            <div class="col-md-6">
                                <input id="apellido" type="text" class="form-control{{ $errors->has('apellido') ? ' is-invalid' : '' }}" name="apellido" value="{{ $estudiante->apellido }}" required autofocus>

                                @if ($errors->has('apellido'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('apellido') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="cedula" class="col-md-4 col-form-label text-md-right">Cedula</label>

                            <div class="col-md-6">
                                <input id="cedula" type="text" class="form-control{{ $errors->has('cedula') ? ' is-invalid' : '' }}" name="cedula" value="{{ $estudiante->cedula }}" required autofocus>

                                @if ($errors->has('cedula'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('cedula') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="carrera" class="col-md-4 col-form-label text-md-right">Carrera</label>

                            <div class="col-md-6">
                                <input id="carrera" type="text" class="form-control{{ $errors->has('carrera') ? ' is-invalid' : '' }}" name="carrera" value="{{ $estudiante->carrera }}" required autofocus>

                                @if ($errors->has('carrera'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('carrera') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="telefono" class="col-md-4 col-form-label text-md-right">Telefono</label>

                            <div class="col-md-6">
                                <input id="telefono" type="text" class="form-control{{ $errors->has('telefono') ? ' is-invalid' : '' }}" name="telefono" value="{{ $estudiante->telefono }}" required autofocus>

                                @if ($errors->has('telefono'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('telefono') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="correo" class="col-md-4 col-form-label text-md-right">Correo electronico</label>

                            <div class="col-md-6">
                                <input id="correo" type="email" class="form-control{{ $errors->has('correo') ? ' is-invalid' : '' }}" name="correo" value="{{ $estudiante->correo }}" required autofocus>

                                @if ($errors->has('correo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('correo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Actualizar
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/estudiante/index.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @forelse ($estudiantes as $estudiante)
        @if ($loop->first)
        <div class="col-md-8 text-center">
            <h1>Estudiantes Actuales</h1>
        </div>
        @endif
        
        <div class="col-md-8 mt-2">
            <div class="card">
                <div class="card-header"> <a class="btn" href="{{ route('estudiante.show', $estudiante) }}"> {{$estudiante->title}} </a></div>
                <div class="card-body">
                <div>
                    <p>Nombre: {{$estudiante->nombre}}</p>
                    <p>Apellido: {{$estudiante->apellido}}</p>
                    <p>Cedula: {{$estudiante->cedula}}</p>
                    <p>Carrera: {{$estudiante->carrera}}</p>
                    <p>Telefono: {{$estudiante->telefono}}</p>
                    <p>Correo Electronico: {{$estudiante->correo}}</p>
                </div>
                </div>
            </div>
        </div>

         <div class=" d-inline-flex ">
            <a href="{{route('estudiante.edit', $estudiante)}}" class="btn btn-outline-success btn-md mr-2">Editar</a>
                <form action="{{route('estudiante.destroy', $estudiante)}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <button type="submit" href="{{route('estudiante.edit', $estudiante)}}" class="btn btn-danger btn-md">Borrar</button>
                    </form>
        </div>


        @empty
        <div class="col-md-8 text-center">
            <h1>Aun no hay esudiantes</h1>
        </div>
        @endforelse

       

    </div>
</div>
@endsection

resources/views/estudiante/show.blade.php
@extends('master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
    
        <div class="col-md-8 text-center">
            <h1>Estudiantes Disponibles</h1>
        </div>
              
        <div class="col-md-8 mt-2">
            <div class="card">
                <div class="card-body">
                <div>
                    <p>Nombre: {{$estudiante->nombre}}</p>
                    <p>Apellido: {{$estudiante->apellido}}</p>
                    <p>Cedula: {{$estudiante->cedula}}</p>
                    <p>Carrera: {{$estudiante->carrera}}</p>
                    <p>Telefono: {{$estudiante->telefono}}</p>
                    <p>Correo Electronico: {{$estudiante->correo}}</p>
                </div>
                </div>
            </div>
        </div>
      
    </div>
</div>
@endsection

resources/views/estudiante/update.blade.php
<h1>sdfghjk</h1>